### ISSUE TITLE
Fix letter size box of Cases e/ou Deaths

### ISSUE THREAD

**Issue by gabrielcesar** [gabrielcesar/covid#2]
Due to an exponential increase in Confirmed Cases and Deaths, the information needs to be adapted for better visualization.

[https://gabrielcesar.github.io/covid/](https://gabrielcesar.github.io/covid/)

**Comment by m1ga** [comment]
I can give it a try to see what looks best

**Comment by mraguso2** [comment]
This would likely impact font size updates but @gabrielcesar would you be interested in adding commas to all the data points?

@m1ga this would likely make the number larger impacting how you might try handling size constraints

**Comment by mraguso2** [comment]
*I would work on adding commas to all the data points...{1,000,000}

**Comment by m1ga** [comment]
I think adding some more space (one digit more) would already help. 
And perhaps putting them in two rows (in the header) would also be better.

**Comment by mraguso2** [comment]
pull request #3 adds commas to numbers if you're interested :)

You might need to add more space to account for commas if @gabrielcesar decides to include them

**Comment by m1ga** [comment]
@gabrielcesar https://github.com/gabrielcesar/covid/pull/4

**Comment by gabrielcesar** [comment]
Thanks for the collaboration @m1ga and @mraguso2.
